import Logo1 from "@assets/svgs/logo1.svg";

export const rows = [
  {
    id: "001",
    franchise: "Vaclucia Motors",
    detailer: {
      name: "Ahmad Septiwan",
      avatar: Logo1,
    },
    customer: "Kaiya Botar",
    date: "04-05-2025",
    service: "Car Wash",
    vehicle: "Phoenix",
    status: "Completed",
    location: "2972 Westheimer Rd. Santa Ana, Illinois 85486 ",
    numberDetails: 20,
    earning: "$30.00",
    joined: "10-01-2025",
    jobComplete: 10,
    booking: 20,
    lastBooking: "10-june-2025",
    spending: "$30.00",
    amount: "$60.00",
    payMethodth: "Stripe",
    issueTd: "Negligence",
    incidentTh: "Last Weak My Car .....",
    suggestions: "You're doing good",
    invoice: "Booking Hotel",
    appHelpfull: "Yes",
    recommendapp: "Yes",
    howHelpfullApp: "Yes",
    userSuggestion: "Last week, my car .... ",
    no_detailer:"9999",
    ratingTd:10

  },
  {
    id: "002",
    franchise: "DreamDrive",
    detailer: {
      name: "Erin Vetrov",
      avatar: Logo1,
    },
    customer: "Alfredo Soris",
    date: "04-05-2025",
    service: "Detailing",
    vehicle: "Cobra",
    earning: "$0.00",
    status: "In Progress",
    location: "2972 Westheimer Rd. Santa Ana, Illinois 85486 ",
    numberDetails: 20,
    joined: "10-01-2025",
    jobComplete: 10,
    booking: 20,
    lastBooking: "10-june-2025",
    spending: "$0.00",
    amount: "$0.00",
    payMethodth: "Paypal",
    issueTd: "Negligence",
    incidentTh: "Last Weak My Car .....",
    suggestions: "You're doing good",
    invoice: "Booking Hotel",
    appHelpfull: "Yes",
    recommendapp: "Yes",
    howHelpfullApp: "Yes",
    userSuggestion: "Last week, my car .... ",
    no_detailer:"9999",
    ratingTd:10


  },
  {
    id: "003",
    franchise: "Healthride Vehicles",
    detailer: {
      name: "Giancu Batrom",
      avatar: Logo1,
    },
    customer: "Lincoln Gusae",
    date: "04-05-2025",
    service: "Detailing",
    vehicle: "Raptor",
    earning: "$0.00",
    status: "In Progress",
    location: "2972 Westheimer Rd. Santa Ana, Illinois 85486 ",
    numberDetails: 201,
    joined: "10-01-2025",
    jobComplete: 10,
    booking: 20,
    lastBooking: "10-june-2025",
    spending: "$0.00",
    amount: "$0.00",
    payMethodth: "Paypal",
    suggestions: "You're doing good",
    invoice: "Booking Hotel",
    appHelpfull: "Yes",
    recommendapp: "Yes",
    howHelpfullApp: "Yes",
    userSuggestion: "Last week, my car .... ",
    no_detailer:"9999",
    ratingTd:10


  },
  {
    id: "004",
    franchise: "Biwered Motors",
    detailer: {
      name: "Alfredo Rihidl Madsson",
      avatar: Logo1,
    },
    customer: "Aspen Schieffer",
    date: "04-05-2025",
    service: "Detailing",
    vehicle: "Vortex",
    earning: "$20.00",
    status: "Completed",
    location: "2972 Westheimer Rd. Santa Ana, Illinois 85486 ",
    numberDetails: 20,
    joined: "10-01-2025",
    jobComplete: 10,
    booking: 20,
    lastBooking: "10-june-2025",
    spending: "$0.00",
    amount: "$0.00",
    payMethodth: "Paypal",
    suggestions: "You're doing good",
    invoice: "Booking Hotel",
    appHelpfull: "Yes",
    recommendapp: "Yes",
    howHelpfullApp: "Yes",
    userSuggestion: "Last week, my car .... ",
    no_detailer:"9999",
    ratingTd:10


  },
  {
    id: "005",
    franchise: "Fantasy Auto Group",
    detailer: {
      name: "Tachiona Curtis",
      avatar: Logo1,
    },
    customer: "Alfredo Philips",
    date: "04-05-2025",
    service: "Detailing",
    vehicle: "Stingray",
    earning: "$0.00",
    status: "Canceled",
    location: "2972 Westheimer Rd. Santa Ana, Illinois 85486 ",
    numberDetails: 20,
    joined: "10-01-2025",
    jobComplete: 10,
    booking: 20,
    lastBooking: "10-june-2025",
    spending: "$0.00",
    amount: "$0.00",
    payMethodth: "Card",
    issueTd: "Negligence",
    invoice: "Booking Hotel",
    appHelpfull: "Yes",
    recommendapp: "Yes",
    howHelpfullApp: "Yes",
    userSuggestion: "Last week, my car .... ",
    no_detailer:"9999",
    ratingTd:10


  },
];
